#!/bin/bash

apt update && sudo apt upgrade -y

# Install PHP
apt install php7.2 php7.2-cli php7.2-common php7.2-json php7.2-opcache php7.2-mysql php7.2-mbstring php7.2-zip php7.2-fpm php7.2-xml unzip -y

# Apache config
sed -i "s|AllowOverride None|AllowOverride All|g"  /etc/apache2/apache2.conf

# Install dependencies
cd /var/www/perchlaravel
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
sudo chown -R $USER ~/.composer/
composer install

# Laravel Specific
php artisan key:generate